[mesh]
file = "cable2d_axi.msh"

[materials]
# region (cellset name in gmsh) = material key or alias
cu     = "copper"
sc_in  = "semicon"
xlpe   = "xlpe"
sc_out = "semicon"
al     = "aluminum"
cover  = "cover"

[physics.thermal]
type = "steady"
exclude_domain = []  # thermal everywhere

[physics.thermal.bc]
# Standard Robin BC 
# outer = { type = "convection", h = 8.0, Tinf = 293.15 }

# BC interramento equivalente IEC 60287
outer = { type = "buried_iec60287", Tinf = 293.15, burial_depth = 1.3, rho_thermal_soil = 1.3}
axis  = { type = "symmetry" }

[physics.thermal.sources]
cu = { type = "joule_J", J = 1.22e6 }   # A/m^2

[physics.electric]
type = "conduction"          # "electrostatic" or "conduction"
exclude_domain = ["cu"]

[physics.electric.conduction]
nonlinear = true             # if false -> linear conduction with Ïƒ(T,0)
sigma_model = "xlpe_exp"     # apply the exp law on XLPE

sigma0 = 1e-16               # S/m at T0
T0 = 273.15                  # K
alpha = 0.084                # 1/K
beta_mm_per_kV = 0.0645      # mm/kV

[physics.electric.bc]
interface_cu = { type = "dirichlet", phi = 1.0E2 }
outer        = { type = "dirichlet", phi = 0.0 }
axis         = { type = "symmetry"}
